import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'

import {
  createInstance,
  OptimizelyFeature,
  OptimizelyProvider,
  withOptimizely
} from '@optimizely/react-sdk';

const optimizely = createInstance({
  sdkKey: 'KcJRoKbnxrcrRa5QGUSjy'
});

export default function Home() {

  const onClick = () => {
    console.log("click");
    optimizely.track('purchase')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <>
          <Script 
            src="https://cdn.optimizely.com/js/20759430581.js" 
            strategy="beforeInteractive"/>
        </>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Optimizely React SDK Example
        </h1>

        <OptimizelyProvider
            optimizely={optimizely}
            user={{
              id: 'user123',
            }}
        >
          <OptimizelyFeature feature="discount">
              {(enabled, variables) => (
                enabled ? <>Feature Enabled</> : <></>
              )}
          </OptimizelyFeature>
          <OptimizelyFeature feature="discount">
              {(enabled, variables) => (
                `Got a discount of $${variables.amount}`
              )}
          </OptimizelyFeature>
        </OptimizelyProvider>

        <button onClick={onClick}>
          Buy Something
        </button>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
